<?php

namespace App\Services;

class NoteCacheService extends CacheService
{
    public const KEY_TEMPLATE = 'note:%s%s';

    public function getKey(string $phone, string $email): string
    {
        return sprintf(self::KEY_TEMPLATE, $phone, $email);
    }

    public function warmUp()
    {
        parent::warmUp(); // TODO: Change the autogenerated stub
    }
}
